require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/quest_lists", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # QuestList. As you add validations to QuestList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      QuestList.create! valid_attributes
      get quest_lists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      quest_list = QuestList.create! valid_attributes
      get quest_list_url(quest_list)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_quest_list_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      quest_list = QuestList.create! valid_attributes
      get edit_quest_list_url(quest_list)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new QuestList" do
        expect {
          post quest_lists_url, params: { quest_list: valid_attributes }
        }.to change(QuestList, :count).by(1)
      end

      it "redirects to the created quest_list" do
        post quest_lists_url, params: { quest_list: valid_attributes }
        expect(response).to redirect_to(quest_list_url(QuestList.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new QuestList" do
        expect {
          post quest_lists_url, params: { quest_list: invalid_attributes }
        }.to change(QuestList, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post quest_lists_url, params: { quest_list: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested quest_list" do
        quest_list = QuestList.create! valid_attributes
        patch quest_list_url(quest_list), params: { quest_list: new_attributes }
        quest_list.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the quest_list" do
        quest_list = QuestList.create! valid_attributes
        patch quest_list_url(quest_list), params: { quest_list: new_attributes }
        quest_list.reload
        expect(response).to redirect_to(quest_list_url(quest_list))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        quest_list = QuestList.create! valid_attributes
        patch quest_list_url(quest_list), params: { quest_list: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested quest_list" do
      quest_list = QuestList.create! valid_attributes
      expect {
        delete quest_list_url(quest_list)
      }.to change(QuestList, :count).by(-1)
    end

    it "redirects to the quest_lists list" do
      quest_list = QuestList.create! valid_attributes
      delete quest_list_url(quest_list)
      expect(response).to redirect_to(quest_lists_url)
    end
  end
end
