default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: postgres.dgqurhdaiqmmqbmfkblt
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: aws-1-ap-southeast-1.pooler.supabase.com
    port: 5432
    database: postgres

development:
  <<: *default
  database: postgres
  username: postgres.dgqurhdaiqmmqbmfkblt
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: aws-1-ap-southeast-1.pooler.supabase.com
  port: 5432

test:
  <<: *default
  database: quest_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>